CREATE DATABASE store_management ;


CREATE  TABLE stores(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
address VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);


CREATE TABLE suppliers(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
phone VARCHAR(255) NOT NULL ,
email VARCHAR(255) NOT NULL UNIQUE,
brief_data TEXT,
PRIMARY KEY(id)

);


CREATE TABLE products(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
code INTEGER(50) UNIQUE  NOT NULL,
description TEXT,
price DECIMAL(10,2) NOT NULL,
PRIMARY KEY(id),

);


CREATE TABLE supplier_product(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
product_id INTEGER UNSIGNED,
supplier_id INTEGER UNSIGNED,

PRIMARY KEY(id),
FOREIGN KEY(product_id) REFERENCES products(id)
FOREIGN KEY(supplier_id ) REFERENCES suppliers(id),

);


CREATE TABLE store_product(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
product_id INTEGER UNSIGNED,
store_id INTEGER UNSIGNED,

PRIMARY KEY(id),
FOREIGN KEY(product_id) REFERENCES products(id)
FOREIGN KEY(store_id) REFERENCES stores(id),

);



